apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/zaidgabri/spring-k8s-argocd-demo.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-argocd-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true